:concurrency: 2
staging:
  :concurrency: 5
production:
  :concurrency: 10
:queues:
  - high_priority
  - default
  - mailers
  - active_storage_analysis
  - active_storage_purge
:schedule:
  cleanup_expired_tickets:
    every: '12h'
    class: CleanupExpiredTicketsJob
